# This file describes a Fastly Compute package for staging environment

authors = ["jdcajera@gmail.com"]
description = "Simple S3 bucket browser in Go with folder navigation (Staging)"
language = "go"
manifest_version = 3
name = "go-s3browser-staging"
service_id = "fydbgTnL77IvKkZY2yUps4"  # Same as production, as this is a staging version of the same service

[local_server]
  [local_server.backends]
    [local_server.backends.TheOrigin]
      url = "https://geonet-open-data.s3-ap-southeast-2.amazonaws.com"

[scripts]
  build = "go build -buildvcs=false -o bin/main.wasm ."
  env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
  post_init = "go get github.com/fastly/compute-sdk-go@latest"
