name: Deploy to Staging

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    env:
      FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_STAGING_TOKEN }}
      FASTLY_SERVICE_STAGING_ID: ${{ secrets.FASTLY_SERVICE_STAGING_ID }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Fastly CLI
        run: |
          VERSION=$(curl -s https://api.github.com/repos/fastly/cli/releases/latest | jq -r .tag_name)
          wget https://github.com/fastly/cli/releases/download/${VERSION}/fastly_${VERSION}_linux-amd64.tar.gz
          tar -xzf fastly_${VERSION}_linux-amd64.tar.gz
          sudo mv fastly /usr/local/bin/

      - name: Build and Deploy to Staging
        run: |
          echo "Building and deploying to staging environment..."
          fastly compute build
<<<<<<< HEAD
          fastly compute deploy --service-id ${{ secrets.FASTLY_SERVICE_ID }} --env staging --activate false
          echo "Successfully deployed to staging!"
=======
          fastly compute deploy --service-id ${{ secrets.FASTLY_SERVICE_STAGING_ID }} --env staging
          echo "Successfully deployed and activated to staging!"
>>>>>>> 29fbc8a (fix: update staging deployment)
